# Build your first matrix

## matrix

In [1]:
my.data <- 1:20
my.data

A <- matrix(my.data, 4, 5)
A
A[2,3]

B <- matrix(my.data, 4, 5, byrow = T)
B
B[2,5]

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

[1] 10

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20

[1] 10

## rbind

In [2]:
#rbind()
r1 <- c("I", "am", "happy")
r2 <- c("What", "a", "day")
r3 <- c(1, 2, 3)
C <- rbind(r1, r2, r3)
C

[,1] [,2] [,3] 
r1 I    am   happy
r2 What a    day  
r3 1    2    3

## cbind

In [3]:
c1 <- 1:5
c2 <- -1:-5
D <- cbind(c1, c2)
D

c1 c2
[1,] 1  -1
[2,] 2  -2
[3,] 3  -3
[4,] 4  -4
[5,] 5  -5

# Colnames and Rownames

## Named Vectors

In [5]:
Charlie <- 1:5;
Charlie

[1] 1 2 3 4 5

### Give names

In [6]:
names(Charlie) <- c("a", "b", "c", "d", "e")
Charlie
Charlie["d"]
names(Charlie)

a b c d e 
1 2 3 4 5

d 
4

[1] "a" "b" "c" "d" "e"

### Clean names

In [7]:
names(Charlie) <- NULL
Charlie

[1] 1 2 3 4 5

## Naming Matrix Dimensions

In [8]:
temp.vec <- rep(c("a", "B", "zZ"), each=3)
temp.vec

Bravo <- matrix(temp.vec, 3, 3)
Bravo

rownames(Bravo) <- c("How", "are", "you?")
Bravo

colnames(Bravo) <- c("X", "Y", "Z")
Bravo

Bravo["are", "Y"] <- 0
Bravo

rownames(Bravo) <- NULL
Bravo

[1] "a"  "a"  "a"  "B"  "B"  "B"  "zZ" "zZ" "zZ"

[,1] [,2] [,3]
[1,] a    B    zZ  
[2,] a    B    zZ  
[3,] a    B    zZ

[,1] [,2] [,3]
How  a    B    zZ  
are  a    B    zZ  
you? a    B    zZ

X Y Z 
How  a B zZ
are  a B zZ
you? a B zZ

X Y Z 
How  a B zZ
are  a 0 zZ
you? a B zZ

X Y Z 
[1,] a B zZ
[2,] a 0 zZ
[3,] a B zZ