# Build your first matrix

## matrix

In [1]:
my.data <- 1:20
my.data

A <- matrix(my.data, 4, 5)
A
A[2,3]

B <- matrix(my.data, 4, 5, byrow = T)
B
B[2,5]

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

[1] 10

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20

[1] 10

## rbind

In [2]:
#rbind()
r1 <- c("I", "am", "happy")
r2 <- c("What", "a", "day")
r3 <- c(1, 2, 3)
C <- rbind(r1, r2, r3)
C

[,1] [,2] [,3] 
r1 I    am   happy
r2 What a    day  
r3 1    2    3

## cbind

In [3]:
c1 <- 1:5
c2 <- -1:-5
D <- cbind(c1, c2)
D

c1 c2
[1,] 1  -1
[2,] 2  -2
[3,] 3  -3
[4,] 4  -4
[5,] 5  -5

# Colnames and Rownames

## Named Vectors

In [4]:
Charlie <- 1:5;
Charlie

[1] 1 2 3 4 5

### Give names

In [5]:
names(Charlie) <- c("a", "b", "c", "d", "e")
Charlie
Charlie["d"]
names(Charlie)

a b c d e 
1 2 3 4 5

d 
4

[1] "a" "b" "c" "d" "e"

### Clean names

In [6]:
names(Charlie) <- NULL
Charlie

[1] 1 2 3 4 5

## Naming Matrix Dimensions

In [7]:
temp.vec <- rep(c("a", "B", "zZ"), each=3)
temp.vec

Bravo <- matrix(temp.vec, 3, 3)
Bravo

rownames(Bravo) <- c("How", "are", "you?")
Bravo

colnames(Bravo) <- c("X", "Y", "Z")
Bravo

Bravo["are", "Y"] <- 0
Bravo

rownames(Bravo) <- NULL
Bravo

[1] "a"  "a"  "a"  "B"  "B"  "B"  "zZ" "zZ" "zZ"

[,1] [,2] [,3]
[1,] a    B    zZ  
[2,] a    B    zZ  
[3,] a    B    zZ

[,1] [,2] [,3]
How  a    B    zZ  
are  a    B    zZ  
you? a    B    zZ

X Y Z 
How  a B zZ
are  a B zZ
you? a B zZ

X Y Z 
How  a B zZ
are  a 0 zZ
you? a B zZ

X Y Z 
[1,] a B zZ
[2,] a 0 zZ
[3,] a B zZ

# Matrix operations

In [8]:
source("./datasets/4.\ Basketball\ Data.R")

## Games

In [11]:
Games
FieldGoals
MinutesPlayed

2005 2006 2007 2008 2009 2010 2011 2012 2013 2014
KobeBryant     80   77   82   82   73   82   58   78    6   35  
JoeJohnson     82   57   82   79   76   72   60   72   79   80  
LeBronJames    79   78   75   81   76   79   62   76   77   69  
CarmeloAnthony 80   65   77   66   69   77   55   67   77   40  
DwightHoward   82   82   82   79   82   78   54   76   71   41  
ChrisBosh      70   69   67   77   70   77   57   74   79   44  
ChrisPaul      78   64   80   78   45   80   60   70   62   82  
KevinDurant    35   35   80   74   82   78   66   81   81   27  
DerrickRose    40   40   40   81   78   81   39    0   10   51  
DwayneWade     75   51   51   79   77   76   49   69   54   62

2005 2006 2007 2008 2009 2010 2011 2012 2013 2014
KobeBryant     978  813  775  800  716  740  574  738   31  266 
JoeJohnson     632  536  647  620  635  514  423  445  462  446 
LeBronJames    875  772  794  789  768  758  621  765  767  624 
CarmeloAnthony 756  691  728  535  688  684  441  669  743  358 
DwightHoward   468  526  583  560  510  619  416  470  473  251 
ChrisBosh      549  543  507  615  600  524  393  485  492  343 
ChrisPaul      407  381  630  631  314  430  425  412  406  568 
KevinDurant    306  306  587  661  794  711  643  731  849  238 
DerrickRose    208  208  208  574  672  711  302    0   58  338 
DwayneWade     699  472  439  854  719  692  416  569  415  509

2005 2006 2007 2008 2009 2010 2011 2012 2013 2014
KobeBryant     3277 3140 3192 2960 2835 2779 2232 3013  177 1207
JoeJohnson     3340 2359 3343 3124 2886 2554 2127 2642 2575 2791
LeBronJames    3361 3190 3027 3054 2966 3063 2326 2877 2902 2493
CarmeloAnthony 2941 2486 2806 2277 2634 2751 1876 2482 2982 1428
DwightHoward   3021 3023 3088 2821 2843 2935 2070 2722 2396 1223
ChrisBosh      2751 2658 2425 2928 2526 2795 2007 2454 2531 1556
ChrisPaul      2808 2353 3006 3002 1712 2880 2181 2335 2171 2857
KevinDurant    1255 1255 2768 2885 3239 3038 2546 3119 3122  913
DerrickRose    1168 1168 1168 3000 2871 3026 1375    0  311 1530
DwayneWade     2892 1931 1954 3048 2792 2823 1625 2391 1775 1971

## Operations

In [12]:
round(FieldGoals / Games, 1)
round(MinutesPlayed / Games)

2005 2006 2007 2008 2009 2010 2011 2012 2013 2014
KobeBryant     12.2 10.6  9.5  9.8  9.8 9.0   9.9  9.5  5.2 7.6 
JoeJohnson      7.7  9.4  7.9  7.8  8.4 7.1   7.0  6.2  5.8 5.6 
LeBronJames    11.1  9.9 10.6  9.7 10.1 9.6  10.0 10.1 10.0 9.0 
CarmeloAnthony  9.4 10.6  9.5  8.1 10.0 8.9   8.0 10.0  9.6 8.9 
DwightHoward    5.7  6.4  7.1  7.1  6.2 7.9   7.7  6.2  6.7 6.1 
ChrisBosh       7.8  7.9  7.6  8.0  8.6 6.8   6.9  6.6  6.2 7.8 
ChrisPaul       5.2  6.0  7.9  8.1  7.0 5.4   7.1  5.9  6.5 6.9 
KevinDurant     8.7  8.7  7.3  8.9  9.7 9.1   9.7  9.0 10.5 8.8 
DerrickRose     5.2  5.2  5.2  7.1  8.6 8.8   7.7  NaN  5.8 6.6 
DwayneWade      9.3  9.3  8.6 10.8  9.3 9.1   8.5  8.2  7.7 8.2

2005 2006 2007 2008 2009 2010 2011 2012 2013 2014
KobeBryant     41   41   39   36   39   34   38    39  30   34  
JoeJohnson     41   41   41   40   38   35   35    37  33   35  
LeBronJames    43   41   40   38   39   39   38    38  38   36  
CarmeloAnthony 37   38   36   34   38   36   34    37  39   36  
DwightHoward   37   37   38   36   35   38   38    36  34   30  
ChrisBosh      39   39   36   38   36   36   35    33  32   35  
ChrisPaul      36   37   38   38   38   36   36    33  35   35  
KevinDurant    36   36   35   39   40   39   39    39  39   34  
DerrickRose    29   29   29   37   37   37   35   NaN  31   30  
DwayneWade     39   38   38   39   36   37   33    35  33   32

# Visualize with Matplot

In [15]:
matplot(t(FieldGoals/Games), type = "b", pch = 15:18, col = c(1:4, 6))
legend("bottomleft", inset = 0,01, legend = Players, pch = 15:18, col = c(1:4, 6), horiz = F)

matplot(t(FieldGoals/FieldGoalAttempts), type = "b", pch = 15:18, col = c(1:4, 6))
legend("bottomleft", inset = 0,01, legend = Players, pch = 15:18, col = c(1:4, 6), horiz = F)

# Subsetting

In [16]:
x <- c("a", "b", "c", "d", "e")
x
x[c(1, 5)]
x[1]


Games
Games[1:3,6:10]
Games[c(1,10),]
Games[,c("2008", "2009")]
Games[1,]
Games[1, 5]

is.matrix(Games[1,])
is.vector(Games[1,])

Games[1, , drop = F]
Games[1, 5, drop = F]

[1] "a" "b" "c" "d" "e"

[1] "a" "e"

[1] "a"

2005 2006 2007 2008 2009 2010 2011 2012 2013 2014
KobeBryant     80   77   82   82   73   82   58   78    6   35  
JoeJohnson     82   57   82   79   76   72   60   72   79   80  
LeBronJames    79   78   75   81   76   79   62   76   77   69  
CarmeloAnthony 80   65   77   66   69   77   55   67   77   40  
DwightHoward   82   82   82   79   82   78   54   76   71   41  
ChrisBosh      70   69   67   77   70   77   57   74   79   44  
ChrisPaul      78   64   80   78   45   80   60   70   62   82  
KevinDurant    35   35   80   74   82   78   66   81   81   27  
DerrickRose    40   40   40   81   78   81   39    0   10   51  
DwayneWade     75   51   51   79   77   76   49   69   54   62

2010 2011 2012 2013 2014
KobeBryant  82   58   78    6   35  
JoeJohnson  72   60   72   79   80  
LeBronJames 79   62   76   77   69

2005 2006 2007 2008 2009 2010 2011 2012 2013 2014
KobeBryant 80   77   82   82   73   82   58   78    6   35  
DwayneWade 75   51   51   79   77   76   49   69   54   62

2008 2009
KobeBryant     82   73  
JoeJohnson     79   76  
LeBronJames    81   76  
CarmeloAnthony 66   69  
DwightHoward   79   82  
ChrisBosh      77   70  
ChrisPaul      78   45  
KevinDurant    74   82  
DerrickRose    81   78  
DwayneWade     79   77

2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 
  80   77   82   82   73   82   58   78    6   35

[1] 73

[1] FALSE

[1] TRUE

2005 2006 2007 2008 2009 2010 2011 2012 2013 2014
KobeBryant 80   77   82   82   73   82   58   78   6    35

2009
KobeBryant 73